### ISSUE TITLE
Running2.26.0 with external volume gives error using rest 

### ISSUE THREAD

**Issue by Daafip** [oscarfonts/docker-geoserver#48]
Hi all,

We've been using the oscarfonts/geoserver:xx.xx.x for a while now when deploy the [LIWO project](basisinformatie-overstromingen.nl).
When upgrading to a newer version, we noticed the rest API stopped working.
In 2.23.6 this wasn't an issue, when testing with 2.26.0 this issue arose.
We debugged it a little, in the 2.26 the rest API (http://localhost:8080/geoserver/rest/) does work if I specify a volume inside the docker.
When I use an external volume, it no longer works.
If I use the docker.osgeo.org/geoserver:2.26.0 with an external volume, it does work.
I traced it to the initial start-up, on the first run it doesn't work, on the second it does. 
Digging a little deeper its due to the `security.properties`file,  which is almost empty, but if I do add this to the file, it runs fine. 
Is this due to the security layer you add? Would you know of a way to solve this? 
I found a work around which works for us, but would be nice if it works out of the box. 

```yaml
services:
  # .... (other dockers)
  geoserver:
    image: "oscarfonts/geoserver:2.26.0"
    volumes:
      - ./geoserver/data:/var/local/geoserverer
    environment:
      - CATALINA_OPTS=-server -Dorg.geoserver.wfs.getfeature.cachelimit=5000 -Xms8192M -Xmx8192M -Djava.awt.headless=true -Xss4M -XX:SoftRefLRUPolicyMSPerMB=36000 -XX:+UseG1GC -XX:+UseStringDeduplication -XX:NewSize=48M -DGEOSERVER_DATA_DIR=/var/local/geoserver
    ports:
      - "8080:8080"

```
